name: Sheet to Json Workflow

on:
  schedule:
    # every 20 minutes the job will run
    - cron: "*/10 * * * *"
  push:
    branches:
      - master

jobs:
  update-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 19

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm install

      - name: push
        run: |
          bash ./run.sh 2>> /tmp/apidata_err
          echo "the job completed"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          SHEET: ${{ secrets.SHEET }}
      - name: show job status
        if: always()
        run: |
          git checkout master
        env:
          status: ${{job.status}}
          GITHUB_TOKEN: ${{ secrets.github_token }}